const imageFiles = {
  "raw-cambodian-curly-glueless-bundles":["raw-cambodian-curly-glueless-bundles-1.png","raw-cambodian-curly-glueless-bundles-2.png","raw-cambodian-curly-glueless-bundles-3.png"],
  "bouncy-curl":["bouncy-curl-1.jpg","bouncy-curl-2.jpg","bouncy-curl-3.jpg"],
  "once-off-materclass-e-book":["once-off-materclass-e-book-1.png","once-off-materclass-e-book-2.png","once-off-materclass-e-book-3.jpg"],
  "lunna-curls":["lunna-curls-1.jpg","lunna-curls-2.jpg","lunna-curls-3.jpg"],
  "virgin-hd-lace-closures-frontals":["virgin-hd-lace-closures-frontals-1.png","virgin-hd-lace-closures-frontals-2.png","virgin-hd-lace-closures-frontals-3.png"],
  "super-straight-frontal-wig":["super-straight-frontal-wig-1.jpg","super-straight-frontal-wig-2.jpg","super-straight-frontal-wig-3.png"],
  "bodywave-13x4-hd-lace":["bodywave-13x4-hd-lace-1.png","bodywave-13x4-hd-lace-2.png","bodywave-13x4-hd-lace-3.png"],
  "blond-613-bodywave-wig":["blond-613-bodywave-wig-1.jpg","blond-613-bodywave-wig-2.jpg","blond-613-bodywave-wig-3.png"],
  "blond-613-straight-wig":["blond-613-straight-wig-1.png","blond-613-straight-wig-2.png","blond-613-straight-wig-3.png"],
  "deep-curly-wig":["deep-curly-wig-1.jpg","deep-curly-wig-2.png","deep-curly-wig-3.png"],
  "super-straight-bob-wig":["super-straight-bob-wig-1.jpg","super-straight-bob-wig-2.png","super-straight-bob-wig-3.jpg"],
  "613-blond-bob-wig":["613-blond-bob-wig-1.png","613-blond-bob-wig-2.png","613-blond-bob-wig-3.png"],
  "bob-wig-hd-lace":["bob-wig-hd-lace-1.png","bob-wig-hd-lace-2.png","bob-wig-hd-lace-3.png"],
  "raw-cambodian-straight-bundles-full-head":["raw-cambodian-straight-bundles-full-head-1.png","raw-cambodian-straight-bundles-full-head-2.jpg","raw-cambodian-straight-bundles-full-head-3.jpg"],
  "raw-cambodian-curly-glueless-wig-13x4":["raw-cambodian-curly-glueless-wig-13x4-1.png","raw-cambodian-curly-glueless-wig-13x4-2.png","raw-cambodian-curly-glueless-wig-13x4-3.png"],
  "raw-cambodian-natural-straight-wig":["raw-cambodian-natural-straight-wig-1.png","raw-cambodian-natural-straight-wig-2.png","raw-cambodian-natural-straight-wig-3.png"]
};
const $ = (s,c=document)=>c.querySelector(s); const $$=(s,c=document)=>[...c.querySelectorAll(s)];
const money=n=>`R ${Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const stripHtml=s=>{const d=document.createElement('div');d.innerHTML=s||'';return d.textContent.trim()};
const imgPath=(product,index=0)=>`assets/products/${imageFiles[product.handle][index]}`;
let products=[], currentFilter='All', searchTerm='', cart=[], activeProduct=null, detailQty=1;
try{cart=JSON.parse(localStorage.getItem('bambi-bag')||'[]')}catch{cart=[]}
function categories(p){const t=(p.title+' '+stripHtml(p.body_html)).toLowerCase();const c=[];if(/straight|bone/.test(t))c.push('Bone Straight');if(/curl|wave/.test(t))c.push('Curly & Wave');if(/glueless|glue-less|wear & go|wear and go|bob/.test(t))c.push('Wear & Go');if(/raw|cambodian|burmese/.test(t))c.push('Raw Cambodian');if(/hd lace|hd,|hd /.test(t))c.push('HD Lace');return c}
function availableVariants(p){return p.variants.filter(v=>v.available)}
function minPrice(p){const v=p.variants.length?p.variants:[];return v.length?Math.min(...v.map(x=>Number(x.price))):null}
function card(p,dark=false){const min=minPrice(p), avail=availableVariants(p).length>0;return `<article class="product-card" data-handle="${p.handle}"><button class="card-open" data-product="${p.handle}" aria-label="View ${p.title}"><div class="product-card-media"><span class="availability-badge">${avail?'Available':'Sold out'}</span><img src="${imgPath(p)}" alt="${p.title.replace(/"/g,'&quot;')}"></div></button><div class="card-info"><small>${categories(p)[0]||'The collection'}</small><h3>${p.title}</h3><p>${min===null?'Price on enquiry':`From ${money(min)}`}</p></div>${avail?`<button class="quick-add" data-quick="${p.handle}" aria-label="Quick add ${p.title}">Choose options</button>`:''}</article>`}
function renderFeatured(){const handles=['super-straight-frontal-wig','lunna-curls','raw-cambodian-natural-straight-wig','once-off-materclass-e-book'];const list=handles.map(h=>products.find(p=>p.handle===h)).filter(Boolean);$('#featuredProducts').innerHTML=list.map(p=>card(p,true)).join('')}
function filtered(){let list=products.filter(p=>{const matchCat=currentFilter==='All'||categories(p).includes(currentFilter);const matchSearch=!searchTerm||(p.title+' '+stripHtml(p.body_html)).toLowerCase().includes(searchTerm);const matchAvail=$('#availabilityFilter').value!=='available'||availableVariants(p).length>0;return matchCat&&matchSearch&&matchAvail});const sort=$('#sortSelect').value;if(sort==='low')list.sort((a,b)=>(minPrice(a)??Infinity)-(minPrice(b)??Infinity));if(sort==='high')list.sort((a,b)=>(minPrice(b)??-1)-(minPrice(a)??-1));return list}
function renderProducts(){const list=filtered();$('#productGrid').innerHTML=list.map(p=>card(p)).join('');$('#resultCount').textContent=`${list.length} of ${products.length} pieces`;$('#emptyState').hidden=!!list.length;$('#clearFilters').hidden=currentFilter==='All'&&!searchTerm&&$('#availabilityFilter').value==='all'&&$('#sortSelect').value==='featured'}
function setFilter(value,scroll=true){currentFilter=value;$$('.filter').forEach(b=>{const on=b.dataset.filter===value;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});renderProducts();closeAll();if(scroll)$('#catalogue').scrollIntoView({behavior:'smooth'})}
function openDrawer(el){closeAll();$('#overlay').hidden=false;el.hidden=false;void el.offsetWidth;el.classList.add('open');document.body.classList.add('no-scroll');setTimeout(()=>$('.close-button',el)?.focus(),50)}
function closeAll(){[$('#searchDrawer'),$('#bagDrawer')].forEach(d=>{d.classList.remove('open');d.hidden=true});$('#overlay').hidden=true;document.body.classList.remove('no-scroll');$('#mobileNav').hidden=true;$('#menuButton').setAttribute('aria-expanded','false')}
function saveCart(){localStorage.setItem('bambi-bag',JSON.stringify(cart));renderCart()}
function addToCart(p,variant,qty=1){const key=`${p.id}:${variant.id}`;const existing=cart.find(x=>x.key===key);if(existing)existing.qty+=qty;else cart.push({key,productId:p.id,handle:p.handle,title:p.title,variantId:variant.id,variantTitle:variant.title,price:Number(variant.price),qty});saveCart();showToast(`${p.title} added to your bag`)}
function renderCart(){const count=cart.reduce((s,x)=>s+x.qty,0);$('#bagCount').textContent=count;$('#bagTitleCount').textContent=`(${count})`;$('#bagEmpty').hidden=cart.length>0;$('#bagSummary').hidden=!cart.length;$('#bagItems').innerHTML=cart.map(x=>`<article class="bag-item" data-key="${x.key}"><img src="${imgPath(products.find(p=>p.handle===x.handle)||{handle:x.handle})}" alt=""><div><h3>${x.title}</h3><p>${x.variantTitle}</p><div class="qty-control" aria-label="Quantity"><button data-cart-minus="${x.key}" aria-label="Decrease quantity">−</button><span>${x.qty}</span><button data-cart-plus="${x.key}" aria-label="Increase quantity">+</button></div></div><div class="bag-item-price"><strong>${money(x.price*x.qty)}</strong><br><button class="remove-item" data-remove="${x.key}">Remove</button></div></article>`).join('');$('#bagSubtotal').textContent=money(cart.reduce((s,x)=>s+x.price*x.qty,0))}
function showToast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2600)}
function cleanTitle(s){return s.replace(/\s+/g,' ').trim()}
function openProduct(handle){const p=products.find(x=>x.handle===handle);if(!p)return;activeProduct=p;detailQty=1;const vars=p.variants||[],first=vars.find(v=>v.available)||vars[0];const images=imageFiles[p.handle];$('#productDetail').innerHTML=`<div class="detail-gallery"><div class="detail-thumbs">${images.map((f,i)=>`<button class="${i?'':'active'}" data-gallery="${i}" aria-label="View image ${i+1}"><img src="assets/products/${f}" alt=""></button>`).join('')}</div><img class="detail-main-image" id="detailMainImage" src="${imgPath(p)}" alt="${p.title}"></div><div class="detail-copy"><p class="eyebrow">${categories(p).join(' / ')||'Bambï Beauty'}</p><h2 id="productTitle">${p.title}</h2><p class="detail-price" id="detailPrice">${first?money(first.price):'Price on enquiry'}</p><p class="detail-description">${stripHtml(p.body_html)||'A considered piece from the Bambï Beauty collection.'}</p>${vars.length?`<label class="variant-label" for="variantSelect"><span>${p.options?.[0]?.name||'Style'}</span><span>${vars.length} option${vars.length===1?'':'s'}</span></label><select class="variant-select" id="variantSelect">${vars.map(v=>`<option value="${v.id}" ${v.id===first?.id?'selected':''} ${!v.available?'disabled':''}>${cleanTitle(v.title)} — ${money(v.price)}${v.available?'':' — Unavailable'}</option>`).join('')}</select><p class="variant-status ${first?.available?'':'unavailable'}" id="variantStatus">${first?.available?'Available to add':'Currently unavailable'}</p><div class="detail-purchase"><div class="detail-qty"><button id="detailMinus" aria-label="Decrease quantity">−</button><span id="detailQty">1</span><button id="detailPlus" aria-label="Increase quantity">+</button></div><button class="button dark full" id="detailAdd" ${first?.available?'':'disabled'}>Add to bag <span>→</span></button></div>`:'<p class="variant-status unavailable">Please enquire for current options and pricing.</p>'}<p class="detail-note">Each piece is made with care. A minimum 12-business-day processing time applies before nationwide delivery.</p></div>`;$('#productDialog').showModal();document.body.classList.add('no-scroll');setTimeout(()=>$('#productDialog [data-dialog-close]').focus(),40)}
function selectedVariant(){return activeProduct?.variants.find(v=>String(v.id)===$('#variantSelect')?.value)}
function clearFilters(){currentFilter='All';searchTerm='';$('#searchInput').value='';$('#availabilityFilter').value='all';$('#sortSelect').value='featured';setFilter('All',false)}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.scroll){closeAll();document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})}if(b.dataset.filterLink)setFilter(b.dataset.filterLink);if(b.dataset.filter)setFilter(b.dataset.filter);if(b.dataset.product)openProduct(b.dataset.product);if(b.dataset.quick){const p=products.find(x=>x.handle===b.dataset.quick),v=p&&availableVariants(p)[0];openProduct(b.dataset.quick)}if(b.hasAttribute('data-close'))closeAll();if(b.hasAttribute('data-dialog-close')){$('#productDialog').close();document.body.classList.remove('no-scroll')}if(b.hasAttribute('data-notice-close'))$('#noticeDialog').close();if(b.dataset.gallery!==undefined){$('#detailMainImage').src=imgPath(activeProduct,Number(b.dataset.gallery));$$('[data-gallery]').forEach(x=>x.classList.toggle('active',x===b))}if(b.id==='detailMinus'){detailQty=Math.max(1,detailQty-1);$('#detailQty').textContent=detailQty}if(b.id==='detailPlus'){detailQty=Math.min(10,detailQty+1);$('#detailQty').textContent=detailQty}if(b.id==='detailAdd'){const v=selectedVariant();if(v?.available){addToCart(activeProduct,v,detailQty);$('#productDialog').close();document.body.classList.remove('no-scroll');openDrawer($('#bagDrawer'))}}if(b.dataset.cartMinus||b.dataset.cartPlus){const key=b.dataset.cartMinus||b.dataset.cartPlus,item=cart.find(x=>x.key===key);if(item){item.qty+=b.dataset.cartPlus?1:-1;if(item.qty<1)cart=cart.filter(x=>x.key!==key);saveCart()}}if(b.dataset.remove){cart=cart.filter(x=>x.key!==b.dataset.remove);saveCart()}});
$('#menuButton').addEventListener('click',()=>{const open=$('#mobileNav').hidden;closeAll();$('#mobileNav').hidden=!open;$('#menuButton').setAttribute('aria-expanded',open);document.body.classList.toggle('no-scroll',open)});$('#searchButton').addEventListener('click',()=>{openDrawer($('#searchDrawer'));setTimeout(()=>$('#searchInput').focus(),60)});$('#bagButton').addEventListener('click',()=>openDrawer($('#bagDrawer')));$('#overlay').addEventListener('click',closeAll);$('#searchInput').addEventListener('input',e=>{searchTerm=e.target.value.trim().toLowerCase();renderProducts();$('#catalogue').scrollIntoView({behavior:'smooth'})});$('#availabilityFilter').addEventListener('change',renderProducts);$('#sortSelect').addEventListener('change',renderProducts);$('#clearFilters').addEventListener('click',clearFilters);$('#emptyClear').addEventListener('click',clearFilters);$('#variantSelect')?.addEventListener('change',()=>{});$('#productDetail').addEventListener('change',e=>{if(e.target.id!=='variantSelect')return;const v=selectedVariant();$('#detailPrice').textContent=money(v.price);$('#variantStatus').textContent=v.available?'Available to add':'Currently unavailable';$('#variantStatus').classList.toggle('unavailable',!v.available);$('#detailAdd').disabled=!v.available});$('#checkoutButton').addEventListener('click',()=>{closeAll();$('#noticeDialog').showModal()});$('#newsletterForm').addEventListener('submit',e=>{e.preventDefault();$('#newsletterMessage').textContent='Email signup is not connected yet. Please contact bambi.southafrica@gmail.com to join.';e.target.reset()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAll()});$('#year').textContent=new Date().getFullYear();
fetch('data/source-products.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{products=data.products;renderFeatured();renderProducts();renderCart()}).catch(()=>{$('#resultCount').textContent='The collection could not be loaded.';$('#productGrid').innerHTML='<div class="empty-state"><h3>Please run this prototype through a local web server.</h3><p>See README.md for the one-line command.</p></div>'});
